import static gregtech.api.GTValues.*

// Random recipe tweaks so things are unified

crafting.remove('biomesoplenty:sand_from_dried_sand')
mods.gregtech.chemical_bath.recipeBuilder()
    .inputs(item('biomesoplenty:dried_sand'))
    .fluidInputs(fluid("water") * 100)
    .outputs(item('minecraft:sand'))
    .duration(20) 
    .EUt(VA[ULV])
    .buildAndRegister()

// (White) sandstone unification
crafting.removeByOutput(item('biomesoplenty:white_sandstone'))
mods.gregtech.compressor.recipeBuilder()
    .inputs(item('biomesoplenty:white_sand') * 4)
    .outputs(item('biomesoplenty:white_sandstone'))
    .duration(300) 
    .EUt(2)
    .buildAndRegister()
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('biomesoplenty:white_sandstone', 2))
    .outputs(item('biomesoplenty:white_sandstone'))
    .circuitMeta(1)
    .duration(50) 
    .EUt(4)
    .buildAndRegister()

crafting.removeByOutput(item('biomesoplenty:white_sandstone', 1))
mods.gregtech.laser_engraver.recipeBuilder()
    .inputs(item('biomesoplenty:white_sandstone', 2))
    .notConsumable(ore('craftingLensWhite'))
    .outputs(item('biomesoplenty:white_sandstone', 1))
    .duration(50) 
    .EUt(16)
    .buildAndRegister()

crafting.removeByOutput(item('biomesoplenty:white_sandstone', 2) * 4)
mods.gregtech.assembler.recipeBuilder()
    .inputs(item('biomesoplenty:white_sandstone'))
    .outputs(item('biomesoplenty:white_sandstone', 2))
    .circuitMeta(1)
    .duration(50) 
    .EUt(4)
    .buildAndRegister()

crafting.removeByOutput(item('biomesoplenty:other_slab', 1))
crafting.shapedBuilder()
        .name('biomesoplenty/misc/white_sandstone_slab_saw')
        .output(item('biomesoplenty:other_slab', 1))
        .matrix('sS')
        .key("s", ore("toolSaw"))
        .key("S", item('biomesoplenty:white_sandstone'))
        .register()
mods.gregtech.cutter.recipeBuilder()
    .inputs(item('biomesoplenty:white_sandstone'))
    .outputs(item('biomesoplenty:other_slab', 1) * 2)
    .duration(25) 
    .EUt(7)
    .buildAndRegister()

mods.gregtech.assembler.recipeBuilder()
    .inputs(item('biomesoplenty:white_sandstone') * 6)
    .outputs(item('biomesoplenty:white_sandstone_stairs') * 4)
    .circuitMeta(7)
    .duration(100) 
    .EUt(1)
    .buildAndRegister()

// Blood "chain"
mods.gregtech.centrifuge.recipeBuilder()
    .inputs(item('biomesoplenty:fleshchunk'))
    .fluidOutputs(fluid('gtfo_blood') * 100)
    .duration(100) 
    .EUt(VA[LV])
    .buildAndRegister()
crafting.removeByOutput(item('biomesoplenty:flesh'))
mods.gregtech.compressor.recipeBuilder()
    .inputs(item('biomesoplenty:fleshchunk') * 4)
    .outputs(item('biomesoplenty:flesh'))
    .duration(300) 
    .EUt(2)
    .buildAndRegister()
mods.gregtech.macerator.recipeBuilder()
    .inputs(item('biomesoplenty:flesh'))
    .outputs(item('biomesoplenty:fleshchunk'), item('biomesoplenty:fleshchunk'))
    .chancedOutput(item('biomesoplenty:fleshchunk'), 5000, 0)
    .chancedOutput(item('biomesoplenty:fleshchunk'), 2500, 0)
    .duration(200) 
    .EUt(2)
    .buildAndRegister()

mods.gregtech.vacuum_freezer.recipeBuilder()
    .inputs(item('minecraft:ice'))
    .outputs(item('biomesoplenty:hard_ice'))
    .duration(100) 
    .EUt(VA[LV])
    .buildAndRegister()

crafting.remove('biomesoplenty:mud_from_dirt')
mods.gregtech.chemical_bath.recipeBuilder()
    .inputs(ore('dirt'))
    .fluidInputs(fluid("water") * 100)
    .outputs(item('biomesoplenty:mud'))
    .duration(20) 
    .EUt(VA[ULV])
    .buildAndRegister()

// Not the bees!
mods.gregtech.fluid_solidifier.recipeBuilder()
    .fluidInputs(fluid("honey") * 144)
    .notConsumable(metaitem('shape.mold.block'))
    .outputs(item('biomesoplenty:honey_block'))
    .duration(6) 
    .EUt(VA[ULV])
    .buildAndRegister()
mods.gregtech.extractor.recipeBuilder()
    .inputs(item('biomesoplenty:honey_block'))
    .fluidOutputs(fluid("honey") * 144)
    .duration(6) 
    .EUt(VA[LV])
    .buildAndRegister()
